version: "3.8"

services:
  analyzr:
    image: ezeslucky441/analyzr:v1.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://analyzr:analyzr@db:5432/analyzr
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/heartbeat"]
      interval: 10s   # Increased interval to avoid frequent checks
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: analyzr
      POSTGRES_USER: analyzr
      POSTGRES_PASSWORD: analyzr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "analyzr", "-d", "analyzr"]
      interval: 10s  # Increased interval for better resource management
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
