---
services:
  analyzr:
    image: ezeslucky441/analyzr
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://analyzr:analyzr@db:5432/analyzr
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: analyzr
      POSTGRES_USER: analyzr
      POSTGRES_PASSWORD: analyzr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
