name: 'Bug Report'
description: Create a bug report  for Analyzr
body: 
  - type: textarea
    attributes:
     label: Describe the Bug
     description: A clear and concise description of what th ebug is.
    validation:
     required: true
  - type: dropdown
    attributes:
      label: Database
      description: What database are you using?
      options:
        - PostgreSQl
        -  MySQL
        - Cloud   
    validation:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy  and past any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type:  input
    attributes:
      label: Which Analyzr verson are you using?
      description: 'For example: Chrome, Edge, Firefox, etc'
  - type: input
    attributes:
      label: Which browser are you using? 
      description: 'For example: Chrome, Edge, Firefox, etc'
  - type: input
    attributes:
      label: How are you deploying your application? 
      description: 'For example: Vercel, Railway, Docker, etc'          