

name: Node.js CI

on: [push]

env:
  DATABASE_TYPE: postgresql
  SKIP_DB_CHECK: 1

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      env:
        DATABASE_TYPE: ${{ matrix.db-type }}
    - run: npm install --global yarn
    - run: yarn install
    - run: yarn test
    - run: yarn build
